# Project: Scriptin Dept and Lighting
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Scripting\ Dept\ dan\ Lighting/mainScriptingDeptandLighting.o"
LINKOBJ  = "Scripting Dept dan Lighting/mainScriptingDeptandLighting.o"
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = "Scripting Dept and Lighting.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"Scripting\ Dept\ dan\ Lighting/mainScriptingDeptandLighting.o": Scripting\ Dept\ dan\ Lighting/mainScriptingDeptandLighting.cpp
	$(CPP) -c "Scripting Dept dan Lighting/mainScriptingDeptandLighting.cpp" -o "Scripting Dept dan Lighting/mainScriptingDeptandLighting.o" $(CXXFLAGS)
